# Generated by Django 3.1.3 on 2022-10-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20221025_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-title',)},
        ),
    ]
